### ISSUE TITLE
utils.py TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Scorpikor** [smartxworks/pySMART#14]
Hi all
Python 3.5.2
pySMART-0.3
I have error:
```
Traceback (most recent call last):
  File "/berta_smartmonitor.py", line 69, in <module>
    from pySMART import Device
  File "/usr/local/lib/python3.5/dist-packages/pySMART/__init__.py", line 102, in <module>
    from .device import Device
  File "/usr/local/lib/python3.5/dist-packages/pySMART/device.py", line 33, in <module>
    from .utils import *
  File "/usr/local/lib/python3.5/dist-packages/pySMART/utils.py", line 125, in <module>
    for line in _stdout.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```
this error is in this code in utils.py 

```
cmd = Popen('smartctl --version', shell=True, stdout=PIPE, stderr=PIPE)
_stdout, _stderr = cmd.communicate()
if _stdout == '':
    raise Exception(
        "Required package 'smartmontools' is not installed, or 'smartctl'\n"
        "component is not on the system path. Please install and try again.")
else:
    for line in _stdout.split('\n'):
        if 'release' in line:
            print (line)
            _ma, _mi = line.strip().split(' ')[2].split('.')
            print ("_ma=", _ma, "_mi=", _mi, "_req_ma=",_req_ma)
            if (int(_ma) < _req_ma or
                    (int(_ma) == _req_ma and int(_mi) < _req_mi)):
                raise Exception(
                    "Installed version of smartctl [{0}.{1}] is below the "
                    "minimum requirement of [{2}.{3}]. Please upgrade and "
                    "try again.".format(_ma, _mi, _req_ma, _req_mi))

```
line that works without error
`for line in _stdout.decode().split('\n'):`

sorry for my English

**Comment by DPSB** [comment]
Try:
`python -m pip list`

You are probably using 
```
Package        Version
-------------- -------
pySMART        0.3
```
This is pySMART-0.3 which can be installed/updated by:
`python -m pip install pysmart --upgrade`

# To install the github version:
Run the following command, but note that **this will overwrite the pySMART-0.3 files**
`python -m pip.install pysmart.smartx --upgrade`

The output from
`python -m pip list`
should now look like this:
```
Package        Version
-------------- -------
pySMART        0.3
pySMART.smartx 0.3.8
```

# If you want a clean setup:
* with the latest bugfixes from the github version 
* and you **don't** need the old pysmart-0.3 version:

_Note: This will also remove the files used by pysmart.smartx **(if already installed)**_ 
`python -m pip uninstall pysmart -y`

## To install now the latest version from [https://github.com/smartxworks/pySMART/](https://github.com/smartxworks/pySMART/) use:
_Note: If pysmart.smartx was already installed and has now been removed by the command above, then you first need to uninstall `python -m pip uninstall pysmart.smartx -y` before the following command will actually work_
## `python -m pip install pysmart.smartx --upgrade `

Now check again the installed packages:
`python -m pip list`
```
Package        Version
-------------- -------
pySMART.smartx 0.3.8
```
