### ISSUE TITLE
Release 0.3.6 on github?

### ISSUE THREAD

**Issue by filippog** [smartxworks/pySMART#8]
Hi!
thanks for taking care of pysmart! I noticed the release on pypi is 0.3.6 but `__init__.py` on github still has 0.3.5, would it be possible to upload the 0.3.6 release/code on github too?

thanks!

**Comment by winkidney** [comment]
Thanks, will be issued : )

**Comment by winkidney** [comment]
Sorry, I found that the pypi version is the same as it on github (the only difference is the version-number), don't worry about the new feature, they are all in pypi version.
Now I have no access to this source repo. Maybe @kylezh  or @hushwings can help you : ) with your issue or pull request.

**Comment by winkidney** [comment]
v0.3.7 will be issued : ), closed.
